### ISSUE TITLE
Серверное приложение после распаковки не запускается.

### ISSUE THREAD

**Issue by freeShlak** [freeShlak/ConnectiveGamesTestTask#1]
Серверное приложение после распаковки не запускается, стабильно выдавая NullPointerException.

> Exception in thread "main"  #java.lang.NullPointerException
> 
>     at gameServer.ServerSettings.setLogDecoder(ServerSettings.java:33)
> 
>     at gameServer.ServerSettings.<init>(ServerSettings.java:25)
> 
>     at StartServer.main(StartServer.java:36)

**Comment by freeShlak** [comment]
Bug was fixed.
